# Generated by Django 5.2.3 on 2025-07-21 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyperscaler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_token', models.CharField(max_length=255)),
                ('repo_owner', models.CharField(max_length=255)),
                ('repo_name', models.CharField(max_length=255)),
                ('workflow_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'git_credentials',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='hyperscaler.cloudcredential')),
                ('git', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='hyperscaler.gitcredentials')),
            ],
            options={
                'db_table': 'environments',
            },
        ),
    ]
