# Generated by Django 5.2.3 on 2025-07-21 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyperscaler', '0002_gitcredentials_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudcredential',
            name='cloud_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='env_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gitcredentials',
            name='git_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='cloud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='hyperscaler.cloudcredential'),
        ),
    ]
