# Generated by Django 5.2.3 on 2025-07-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyperscaler', '0003_cloudcredential_cloud_id_environment_env_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
