# Generated by Django 5.2.3 on 2025-07-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyperscaler', '0004_environment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudcredential',
            name='unique_Name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='inactive', max_length=20),
        ),
    ]
