# Generated by Django 5.2.3 on 2025-07-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyperscaler', '0006_gitcredentials_unique_name_alter_environment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('new', 'New'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('failed', 'Failed'), ('deleting', 'Deleting')], default='new', max_length=20),
        ),
    ]
