# Generated by Django 5.2.3 on 2025-07-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyperscaler', '0007_alter_environment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitcredentials',
            name='branch_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
