# Generated by Django 5.2.3 on 2025-07-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyperscaler', '0008_gitcredentials_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitcredentials',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
