# Generated by Django 5.2.3 on 2025-07-31 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyperscaler', '0009_alter_gitcredentials_branch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitcredentials',
            name='branch_name',
        ),
    ]
